config/routes.rb
Myscrumboard::Application.routes.draw do

  resources :user_collaborates_on_boards

  get "contact/index"

  get "about/index"

  get "account/index"
 
  get "boards/invite"
  
  
  resources :stories
	devise_for :users, :path => "auth", :path_names => { :sign_in => 'login', :sign_out => 'logout', :password => 'secret', :confirmation => 'verification', :unlock => 'unblock', :registration => 'register', :sign_up => 'cmon_let_me_in' }
  resources :boards
  
  post "boards/invitecreate"
  
  match "/about" => "about#index"
  match "/contact" => "contact#index"
  match "/home" => "home#index"
  match "/user" => "user#index"
  match "/account" => "account#index"
  match "/boards/invite/:id" => "boards#invite"
  match "/boards/invitecreate" => "boards#invitecreate"
	root :to => "home#index"










end

app/models/user_collaborates_on_board.rb
class UserCollaboratesOnBoard < ActiveRecord::Base
end

app/controllers/user_collaborates_on_boards_controller.rb
class UserCollaboratesOnBoardsController < ApplicationController
  # GET /user_collaborates_on_boards
  # GET /user_collaborates_on_boards.json
  def index
    @user_collaborates_on_boards = UserCollaboratesOnBoard.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @user_collaborates_on_boards }
    end
  end

  # GET /user_collaborates_on_boards/1
  # GET /user_collaborates_on_boards/1.json
  def show
    @user_collaborates_on_board = UserCollaboratesOnBoard.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user_collaborates_on_board }
    end
  end

  # GET /user_collaborates_on_boards/new
  # GET /user_collaborates_on_boards/new.json
  def new
    @user_collaborates_on_board = UserCollaboratesOnBoard.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user_collaborates_on_board }
    end
  end

  # GET /user_collaborates_on_boards/1/edit
  def edit
    @user_collaborates_on_board = UserCollaboratesOnBoard.find(params[:id])
  end

  # POST /user_collaborates_on_boards
  # POST /user_collaborates_on_boards.json
  def create
    @user_collaborates_on_board = UserCollaboratesOnBoard.new(params[:user_collaborates_on_board])

    respond_to do |format|
      if @user_collaborates_on_board.save
        format.html { redirect_to @user_collaborates_on_board, notice: 'User collaborates on board was successfully created.' }
        format.json { render json: @user_collaborates_on_board, status: :created, location: @user_collaborates_on_board }
      else
        format.html { render action: "new" }
        format.json { render json: @user_collaborates_on_board.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /user_collaborates_on_boards/1
  # PUT /user_collaborates_on_boards/1.json
  def update
    @user_collaborates_on_board = UserCollaboratesOnBoard.find(params[:id])

    respond_to do |format|
      if @user_collaborates_on_board.update_attributes(params[:user_collaborates_on_board])
        format.html { redirect_to @user_collaborates_on_board, notice: 'User collaborates on board was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user_collaborates_on_board.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_collaborates_on_boards/1
  # DELETE /user_collaborates_on_boards/1.json
  def destroy
    @user_collaborates_on_board = UserCollaboratesOnBoard.find(params[:id])
    @user_collaborates_on_board.destroy

    respond_to do |format|
      format.html { redirect_to user_collaborates_on_boards_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/user_collaborates_on_boards_helper.rb
module UserCollaboratesOnBoardsHelper
end

app/views/user_collaborates_on_boards/_form.html.erb
<%= form_for(@user_collaborates_on_board) do |f| %>
  <% if @user_collaborates_on_board.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_collaborates_on_board.errors.count, "error") %> prohibited this user_collaborates_on_board from being saved:</h2>

      <ul>
      <% @user_collaborates_on_board.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :userid %><br />
    <%= f.number_field :userid %>
  </div>
  <div class="field">
    <%= f.label :boardid %><br />
    <%= f.number_field :boardid %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_collaborates_on_boards/edit.html.erb
<h1>Editing user_collaborates_on_board</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_collaborates_on_board %> |
<%= link_to 'Back', user_collaborates_on_boards_path %>

app/views/user_collaborates_on_boards/index.html.erb
<h1>Listing user_collaborates_on_boards</h1>

<table>
  <tr>
    <th>Userid</th>
    <th>Boardid</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @user_collaborates_on_boards.each do |user_collaborates_on_board| %>
  <tr>
    <td><%= user_collaborates_on_board.userid %></td>
    <td><%= user_collaborates_on_board.boardid %></td>
    <td><%= link_to 'Show', user_collaborates_on_board %></td>
    <td><%= link_to 'Edit', edit_user_collaborates_on_board_path(user_collaborates_on_board) %></td>
    <td><%= link_to 'Destroy', user_collaborates_on_board, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User collaborates on board', new_user_collaborates_on_board_path %>

app/views/user_collaborates_on_boards/new.html.erb
<h1>New user_collaborates_on_board</h1>

<%= render 'form' %>

<%= link_to 'Back', user_collaborates_on_boards_path %>

app/views/user_collaborates_on_boards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Userid:</b>
  <%= @user_collaborates_on_board.userid %>
</p>

<p>
  <b>Boardid:</b>
  <%= @user_collaborates_on_board.boardid %>
</p>


<%= link_to 'Edit', edit_user_collaborates_on_board_path(@user_collaborates_on_board) %> |
<%= link_to 'Back', user_collaborates_on_boards_path %>