config/routes.rb
Myscrumboard::Application.routes.draw do

  resources :user_collaborates_on_boards

  get "contact/index"

  get "about/index"

  get "account/index"
 
  get "boards/invite"
  
  
  resources :stories
	devise_for :users, :path => "auth", :path_names => { :sign_in => 'login', :sign_out => 'logout', :password => 'secret', :confirmation => 'verification', :unlock => 'unblock', :registration => 'register', :sign_up => 'cmon_let_me_in' }
  resources :boards
  
  post "boards/invitecreate"
  
  match "/about" => "about#index"
  match "/contact" => "contact#index"
  match "/home" => "home#index"
  match "/user" => "user#index"
  match "/account" => "account#index"
  match "/boards/invite/:id" => "boards#invite"
  match "/boards/invitecreate" => "boards#invitecreate"
	root :to => "home#index"










end

app/models/story.rb
class Story < ActiveRecord::Base
	def self.findAllStoriesOfBoard(id)
		conditions = {}
		conditions[:boardid] = id
		self.find(:all, :conditions => conditions)
	end
	def self.findStoriesOfBoard(id,lane)
		conditions = {}
		conditions[:boardid] = id
		conditions[:lane]=lane
		self.find(:all, :conditions => conditions)
	end
	
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
require 'eventmachine'
require 'faye'

  # GET /stories
  # GET /stories.json
  def index
    @stories = Story.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @stories }
    end
  end

  # GET /stories/1
  # GET /stories/1.json
  def show
    @story = Story.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @story }
    end
  end

  # GET /stories/new
  # GET /stories/new.json
  def new
    @story = Story.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @story }
    end
  end

  # GET /stories/1/edit
  def edit
    @story = Story.find(params[:id])
  end

  # POST /stories
  # POST /stories.json
  def create
    @story = Story.new(params[:story])

    respond_to do |format|
      if @story.save
	  
		message = {:channel => "/boards/#{@story.boardid}", :data => { :text=>@story.to_json, :destroy=>false.to_json}}
		uri = URI.parse("http://faye.dev-ice.com/faye")
		
		puts(@story.to_json)
		Net::HTTP.post_form(uri, :message => message.to_json)
		
        format.html { redirect_to @story, notice: 'Story was successfully created.' }
        format.json { render json: @story, status: :created, location: @story }
      else
        format.html { render action: "new" }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /stories/1
  # PUT /stories/1.json
  def update
    @story = Story.find(params[:id])

    respond_to do |format|
      if @story.update_attributes(params[:story])
        
		message = {:channel => "/boards/#{@story.boardid}", :data => { :text=>@story.to_json, :destroy=>false.to_json}}
		uri = URI.parse("http://faye.dev-ice.com/faye")
		
		Net::HTTP.post_form(uri, :message => message.to_json)
		
		format.html { redirect_to @story, notice: 'Story was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stories/1
  # DELETE /stories/1.json
  def destroy
    @story = Story.find(params[:id])
    
	message = {:channel => "/boards/#{@story.boardid}", :data => { :text=>@story.to_json, :destroy=>true.to_json}}
	uri = URI.parse("http://faye.dev-ice.com/faye")
		
	Net::HTTP.post_form(uri, :message => message.to_json)
	@story.destroy
    respond_to do |format|
      format.html { redirect_to stories_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/stories/_form.html.erb
<%= form_for(@story) do |f| %>
  <% if @story.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@story.errors.count, "error") %> prohibited this story from being saved:</h2>

      <ul>
      <% @story.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br />
    <%= f.number_field :id %>
  </div>
  <div class="field">
    <%= f.label :boardid %><br />
    <%= f.number_field :boardid %>
  </div>
  <div class="field">
    <%= f.label :text %><br />
    <%= f.text_area :text %>
  </div>
  <div class="field">
    <%= f.label :lane %><br />
    <%= f.text_field :lane %>
  </div>
  <div class="field">
    <%= f.label :color %><br />
    <%= f.text_field :color %>
  </div>
  <div class="field">
    <%= f.label :lastmodif %><br />
    <%= f.number_field :lastmodif %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stories/edit.html.erb
<h1>Editing story</h1>

<%= render 'form' %>

<%= link_to 'Show', @story %> |
<%= link_to 'Back', stories_path %>

app/views/stories/index.html.erb
<h1>Listing stories</h1>

<table>
  <tr>
    <th>Id</th>
    <th>Boardid</th>
    <th>Text</th>
    <th>Lane</th>
    <th>Color</th>
    <th>Lastmodif</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @stories.each do |story| %>
  <tr>
    <td><%= story.id %></td>
    <td><%= story.boardid %></td>
    <td><%= story.text %></td>
    <td><%= story.lane %></td>
    <td><%= story.color %></td>
    <td><%= story.lastmodif %></td>
    <td><%= link_to 'Show', story %></td>
    <td><%= link_to 'Edit', edit_story_path(story) %></td>
    <td><%= link_to 'Destroy', story, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Story', new_story_path %>

app/views/stories/new.html.erb
<h1>New story</h1>

<%= render 'form' %>

<%= link_to 'Back', stories_path %>

app/views/stories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id:</b>
  <%= @story.id %>
</p>

<p>
  <b>Boardid:</b>
  <%= @story.boardid %>
</p>

<p>
  <b>Text:</b>
  <%= @story.text %>
</p>

<p>
  <b>Lane:</b>
  <%= @story.lane %>
</p>

<p>
  <b>Color:</b>
  <%= @story.color %>
</p>

<p>
  <b>Lastmodif:</b>
  <%= @story.lastmodif %>
</p>


<%= link_to 'Edit', edit_story_path(@story) %> |
<%= link_to 'Back', stories_path %>