config/routes.rb
Myscrumboard::Application.routes.draw do

  resources :user_collaborates_on_boards

  get "contact/index"

  get "about/index"

  get "account/index"
 
  get "boards/invite"
  
  
  resources :stories
	devise_for :users, :path => "auth", :path_names => { :sign_in => 'login', :sign_out => 'logout', :password => 'secret', :confirmation => 'verification', :unlock => 'unblock', :registration => 'register', :sign_up => 'cmon_let_me_in' }
  resources :boards
  
  post "boards/invitecreate"
  
  match "/about" => "about#index"
  match "/contact" => "contact#index"
  match "/home" => "home#index"
  match "/user" => "user#index"
  match "/account" => "account#index"
  match "/boards/invite/:id" => "boards#invite"
  match "/boards/invitecreate" => "boards#invitecreate"
	root :to => "home#index"










end

app/models/board.rb
class Board < ActiveRecord::Base

	def self.getUserBoards(id)
	
	Board.where("boards.ownerid = ? or boards.id in (select boardid from user_collaborates_on_boards where userid = ?)",id,id)	
	
	end

end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
	before_filter :authenticate_user!
  # GET /boards
  # GET /boards.json
  def index
	unless user_signed_in?
		redirect_to "/auth/login"
		return
	end
	
    @boards = Board.getUserBoards(current_user.id)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @boards }
    end
  end

  # GET /boards/1
  # GET /boards/1.json
  def show
  @board = Board.find(params[:id])
  gon.boardid=@board.id
  @stories = Story.findAllStoriesOfBoard(params[:id])
	@landed = Story.findStoriesOfBoard(params[:id],"landed")
	@in_flight = Story.findStoriesOfBoard(params[:id],"in-flight")
	@take_off = Story.findStoriesOfBoard(params[:id],"take-off")
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @stories }
    end
  end

  # GET /boards/new
  # GET /boards/new.json
  def new
    @board = Board.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @board }
    end
  end

  # GET /boards/1/edit
  def edit
    @board = Board.find(params[:id])
  end

  # POST /boards
  # POST /boards.json
  def create
    params[:board][:ownerid] = current_user.id
    @board = Board.new(params[:board])

    respond_to do |format|
      if @board.save
        format.html { redirect_to @board, notice: 'Board was successfully created.' }
        format.json { render json: @board, status: :created, location: @board }
      else
        format.html { render action: "new" }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /boards/1
  # PUT /boards/1.json
  def update

    @board = Board.find(params[:id])

    respond_to do |format|
      if @board.update_attributes(params[:board])
        format.html { redirect_to @board, notice: 'Board was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boards/1
  # DELETE /boards/1.json
  def destroy
    @board = Board.find(params[:id])
    @board.destroy

    respond_to do |format|
      format.html { redirect_to boards_url }
      format.json { head :no_content }
    end
  end
  
  def invite
	@board = Board.find(params[:id])
	
	respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @board }
	end
  end
  
  def invitecreate
	@user = User.find_by_email(params[:email])
	if @user.nil?
	flash[:notice]="No user with that email exists"
	else
	flash[:notice]="User has been added as collaborator"
	@collaboration = UserCollaboratesOnBoard.new()
	
	@collaboration.boardid = params[:boardid]
	@collaboration.userid = @user.id
	
	@collaboration.save
	end
	
	
	redirect_to boards_url
	
  end
end

app/helpers/boards_helper.rb
module BoardsHelper
	def invite_path(board)
		"/boards/invite/#{board.id}"
	end

end

app/views/boards/_form.html.erb
<%= form_for(@board) do |f| %>
  <% if @board.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@board.errors.count, "error") %> prohibited this board from being saved:</h2>

      <ul>
      <% @board.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/boards/edit.html.erb
<h1>Editing board</h1>

<%= render 'form' %>

<%= link_to 'Show', @board %> |
<%= link_to 'Back', boards_path %>

app/views/boards/index.html.erb
<h1>Listing boards</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Actions</th>
  </tr>

<% @boards.each do |board| %>
  <tr>
    <td><%= board.name %></td>
    <td><%= link_to 'Show', board %></td>
    <td><%= link_to 'Edit', edit_board_path(board) %></td>
    <td><%= link_to 'Destroy', board, confirm: 'Are you sure?', method: :delete %></td>
	<td><%= link_to 'Invite', invite_path(board) %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Board', new_board_path %>
<%= link_to('Logout', destroy_user_session_path, :method => :delete) %>

app/views/boards/invite.html.erb
<h1>Add User To Board</h1>

<%= form_tag("/boards/invitecreate", :method => "post") do %>
  <%= label_tag(:email, "Email adress:") %>
  <%= text_field_tag(:email) %>
  <%= submit_tag("Invite") %>
  <%= hidden_field_tag(:boardid, @board.id) %>
<% end %>

<br />

<%= link_to 'New Board', new_board_path %>
<%= link_to('Logout', destroy_user_session_path, :method => :delete) %>

app/views/boards/new.html.erb
<h1>New board</h1>

<%= render 'form' %>

<%= link_to 'Back', boards_path %>

app/views/boards/show.html.erb
<% content_for :javascripts do %>
<%= include_gon %>
<%= javascript_include_tag "http://faye.dev-ice.com/faye.js","faye_client","editable","scrumboard" %>
<% end %>

<div id="toolbox">
			<select id="colorselect">
			  <option>Classic</option>
			  <option>Blue</option>
			  <option>Green</option>
			  <option>Orange</option>
			  <option>Purple</option>
			  <option>Pink</option>
			  <option>Red</option>
			</select>
			<span id="addStory">+</span>
			<hr />
			</div>
			<div id="scrumboard<?php echo $id;?>">
			<div id="columnheaders">
			<h3 class="columnheader">Take Off</h3>
			<h3 class="columnheader">In Flight</h3>
			<h3 class="columnheader">Landed</h3>
			</div>
			<div id="take-off" class="column">
			<% @take_off.each do |story| %>
				<div class="post-it <%= story.color %>" id="ticket<%= story.id %>">
					<div class="window_tools">
					<span class="ui-icon ui-icon-minusthick">minimize</span><span class="ui-icon ui-icon-plusthick">maximize</span><span class="ui-icon ui-icon-closethick">close</span>
					</div>
					<p><%= story.text %></p>
				</div>
				<% end %>
			</div>
			<div id="in-flight" class="column">
			<% @in_flight.each do |story| %>
				<div class="post-it <%= story.color %>" id="ticket<%= story.id %>">
					<div class="window_tools">
					<span class="ui-icon ui-icon-minusthick">minimize</span><span class="ui-icon ui-icon-plusthick">maximize</span><span class="ui-icon ui-icon-closethick">close</span>
					</div>
					<p><%= story.text %></p>
				</div>
				<% end %>
			</div>
			<div id="landed" class="column">
			<% @landed.each do |story| %>
				<div class="post-it <%= story.color %>" id="ticket<%= story.id %>">
					<div class="window_tools">
					<span class="ui-icon ui-icon-minusthick">minimize</span><span class="ui-icon ui-icon-plusthick">maximize</span><span class="ui-icon ui-icon-closethick">close</span>
					</div>
					<p><%= story.text %></p>
				</div>
				<% end %>
			</div>
			</div>