config/routes.rb
Myscrumboard::Application.routes.draw do

  resources :user_collaborates_on_boards

  get "contact/index"

  get "about/index"

  get "account/index"
 
  get "boards/invite"
  
  
  resources :stories
	devise_for :users, :path => "auth", :path_names => { :sign_in => 'login', :sign_out => 'logout', :password => 'secret', :confirmation => 'verification', :unlock => 'unblock', :registration => 'register', :sign_up => 'cmon_let_me_in' }
  resources :boards
  
  post "boards/invitecreate"
  
  match "/about" => "about#index"
  match "/contact" => "contact#index"
  match "/home" => "home#index"
  match "/user" => "user#index"
  match "/account" => "account#index"
  match "/boards/invite/:id" => "boards#invite"
  match "/boards/invitecreate" => "boards#invitecreate"
	root :to => "home#index"










end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>myScrumboard.net</title>
		<%= csrf_meta_tag %>
		<%= stylesheet_link_tag "reset","pngfix","designer_notes","fineliner","style" %>
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.6.3/jquery.min.js" type="text/javascript"></script>
		<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/jquery-ui.min.js" type="text/javascript"></script>
		<link rel="stylesheet" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.0/themes/ui-lightness/jquery-ui.css" type="text/css"/>
		
		
		<%= content_for :javascripts %>  
		
		
	</head>
	<body>
		<div id="container">
			<div id="header">
				<h1 id="header_title">myScrumboard.net</h1>
				<div id="nav">
					<ol>
						<li><%= link_to "Home", home_path %></li>
						<li><%= link_to "My_Scrumboards", boards_path %></li>
						<li><%= link_to "About", about_path %></li>
						<li><%= link_to "Contact", contact_path %></li>
					</ol>
					<hr/>
				</div>
			</div>
			<% if flash[:alert] %>
  <%=flash[:alert]%>
  <%end%>
  <% if flash[:notice] %>
  <%=flash[:notice]%>
  <%end%>
			<%= yield %>
					<div id="footer"><hr />
		
		Made by <a href="http://elepher.com">Nicky Heuperman</a> &amp; <a href="http://gewoon-alexander.nl">Alexander Boeverssen</a>&copy; 2013 All Rights Reserved
		<form action="https://www.paypal.com/cgi-bin/webscr" method="post" id="paypal">
		<input type="hidden" name="cmd" value="_donations">
		<input type="hidden" name="business" value="ebay@runedesk.nl">
		<input type="hidden" name="lc" value="US">
		<input type="hidden" name="item_name" value="myScrumboard.net">
		<input type="hidden" name="no_note" value="0">
		<input type="hidden" name="currency_code" value="EUR">
		<input type="hidden" name="bn" value="PP-DonationsBF:btn_donate_SM.gif:NonHostedGuest">
		<input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_donate_SM.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!">
		<img alt="" border="0" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1">
		</form>

		</div>
		</div>
	</body>
</html>